[tool.poetry]
name = "agents"
version = "0.1.0"
description = "Core agentic logic with LangGraph"
authors = ["Your Name <your@email.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.*"
langchain = "*"
langgraph = "*"
llama-index = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"